Product_reservation/labs/change_tables/routes.py
from flask import Blueprint, render_template, current_app, request
from werkzeug.utils import redirect

from sql_provider import SQLProvider
from dbcon import change_db, work_with_db
import os
from access import login_permission_required


change_tables = Blueprint('change_tables', __name__, template_folder='templates')
provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@change_tables.route('/', methods=['GET', 'POST'])
@login_permission_required
def change_index():
    if request.method == 'GET':
        items = work_with_db(current_app.config['DB_CONFIG'], provider.get('sql_select.sql'))
        print(items)
        return render_template('change_menu.html', res=items, name=[ 'Покупатель', 'Дата заказа', 'Стоимость'])
    else:
        order_id = request.form.get('order_id')
        sql = provider.get('sql_delete_1.sql', order_id=order_id)
        key = change_db(current_app.config['DB_CONFIG'], sql)
        if key:
            return redirect('/redact')

        return 'Error input'


@change_tables.route('/sql_change_1', methods=['GET', 'POST'])
@login_permission_required
def change_tests():
    if request.method == 'GET':
        return render_template('sql_change_1.html')
    else:
        value1 = request.form.get('value1', None)
        value2 = request.form.get('value2', None)
        value3 = request.form.get('value3', None)
        # value4 = request.form.get('value4', None)
        if value1 and value2 and value3:
            sql = provider.get('sql_change_1.sql', gener1=value1, gener2=value2, gener3=value3)
            if not change_db(current_app.config['DB_CONFIG'], sql):
                return 'Error input'
            return redirect('/redact')
        else:
            return 'Not found value'


@change_tables.route('/sql_update_1', methods=['GET', 'POST'])
@login_permission_required
def update_tests():
    if request.method == 'GET':
        return render_template('sql_update_1.html')
    else:
        value1 = request.form.get('value1', None)
        value2 = request.form.get('value2', None)
        value3 = request.form.get('value3', None)
        value4 = request.form.get('value4', None)
        if value1 and value2 and value3 and value4:
            sql = provider.get('sql_update_1.sql', gener1=value1, gener2=value2, gener3=value3, gener4=value4 )
            if not change_db(current_app.config['DB_CONFIG'], sql):
                return 'Error input'
            return redirect('/redact')
        else:
            return 'Not found value'


Product_reservation/labs/change_tables/templates/change_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
    <style>
        .main-table{
            border: 2px solid black;
            padding: 5px 10px;
        }

        .text-style{
            text-align: center;
        }
    </style>
</head>
<body>
<div class="text-style">
    <a href="{{url_for('change_tables.change_tests')}}"><font size="6" face="Times New Roman"> Добавить заказ </font> </a>
    <br>
<!--    <a href="{{url_for('change_tables.update_tests')}}"><font size="6" face="Times New Roman"> Обновить заказ </font> </a>-->
<!--    <br>-->
    <font size="6" face="Times New Roman">Список заказов</font>

<div class="">
    <br>
    <table class="main-table test-style" style="display: inline-block;">
        {% for i in name%}
            <th>{{i}}</th>
        {% endfor %}
        {% for item in res%}
        <tr>
<!--            <td class="main-table"> {{item['order_id']}} </td>-->
            <td class="main-table"> {{item['customer']}} </td>
            <td class="main-table"> {{item['order_date']}} </td>
            <td class="main-table"> {{item['general_cost']}} </td>
            <td>
                <form action="" method="post">
                    <input type=hidden name="order_id" value="{{  item['order_id'] }}">
                    <input type="submit" name="action" value="Удалить">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
    <br>
    <h1>
        <a href="/"> Вернуться назад</a>
    </h1>
</div>
</body>
</html>

Product_reservation/labs/change_tables/templates/sql_change_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
<font size="6" face="Times New Roman">Добавить клиента</font>

<form action="" method="post">
    <br>
<!--    <input type="number" placeholder="id" name="value1">-->
    <input type="text" placeholder="Покупатель" name="value1">
    <input type="date" placeholder="Дата заказа" name="value2">
    <input type="number" placeholder="Стоимость" name="value3">
    <input type="submit" value="Отправить">
    <br>
    <br>
    <a href="{{url_for('change_tables.change_index')}}"> Вернуться назад</a>
</form>

</body>
</html>

Product_reservation/labs/change_tables/templates/sql_change_2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
<font size="6" face="Times New Roman">Добавление нового теста</font>

<form action="" method="post">
    <br>
    <input type="text" placeholder="id" name="value1">
    <input type="text" placeholder="Покупатель" name="value2">
    <input type="text" placeholder="Дата заказа" name="value3">
    <input type="text" placeholder="Стоимость" name="value4">
    <input type="submit" value="Отправить">
    <br>
    <br>
    <a href="{{url_for('change_tables.change_index')}}"> Вернуться назад</a>
</form>

</body>
</html>

Product_reservation/labs/change_tables/templates/sql_update_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
<font size="6" face="Times New Roman">Обновление данных заказа</font>

<form action="" method="post">
    <br>
    <input type="number" placeholder="id" name="value1">
    <input type="text" placeholder="Покупатель" name="value2">
    <input type="date" placeholder="Дата заказа" name="value3">
    <input type="number" placeholder="Стоимость" name="value4">
    <input type="submit" value="Отправить">
    <br>
    <br>
    <a href="{{url_for('change_tables.change_index')}}"> Вернуться назад</a>
</form>

</body>
</html>