Product_reservation/labs/blueprint_query/blueprint_query.py
from flask import Blueprint, render_template, request, current_app
from sql_provider import SQLProvider
from dbcon import get_db_config, work_with_db
from access import login_permission_required, login_required
import os


query_bp = Blueprint('zapros', __name__, template_folder='templates')

provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@query_bp.route('/')
@login_permission_required
def zaproses():
    return render_template("zaproses.html")


@query_bp.route('/input1')
@login_permission_required
def zaprose1_input():
    return render_template("zapros1_input.html")


@query_bp.route('/input2')
@login_permission_required
def zaprose2_input():
    return render_template("zapros2_input.html")


@query_bp.route('/output1', methods=["POST"])
@login_permission_required
def get_sql1():
    if request.method == 'POST':
        price = request.form.get('price')
    sql = provider.get('zap1.sql', price=price)
    print(sql)

    result = work_with_db(current_app.config['DB_CONFIG'], sql)
    if not result:
        return render_template("zapros1_output.html")
    return render_template("zapros1_output.html", items=result)


@query_bp.route('/output2', methods=["POST"])
@login_permission_required
def get_sql2():
    if request.method == 'POST':
        lang = request.form.get('lang')
    sql = provider.get('zap2.sql', lang=lang)
    result = work_with_db(current_app.config['DB_CONFIG'], sql)
    if not result:
        return render_template("zapros2_output.html")
    return render_template("zapros2_output.html", items=result)


Product_reservation/labs/blueprint_query/templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authorization</title>
</head>
<body>
    {% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Login</h3>
        <div class="box">
            <form method="POST" action="/login">
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="password" name="password" placeholder="Your Password">
                    </div>
                </div>
                <div class="field">
                    <label class="checkbox">
                        <input type="checkbox">
                        Remember me
                    </label>
                </div>
                <button class="button is-block is-info is-large is-fullwidth">Login</button>
            </form>
        </div>
    </div>
    {% endblock %}
    <a href="http://127.0.0.1:5001" style="font-size: 25px">Выход</a>
</body>
</html>

Product_reservation/labs/blueprint_query/templates/zapros1_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zapros1</title>
</head>
<style>
    a {
        color: black;
        text-decoration: none;
        font-size: 30px;
    }
</style>
<body>
    <div align="center">
        <p><font size = 6>Показать все заказы, стоимость которых выше заданного значения</font></p>
        <form action={{url_for('zapros.get_sql1')}} method="post">
            <p><font size = 6>Введите стоимость:
                <input type="number" placeholder="price" name="price">
                <input type="submit" value="Отправить">
            </font></p>
            <a href="http://127.0.0.1:5002">Выход в меню</a>
        </form>
    </div>
</body>
</html>

Product_reservation/labs/blueprint_query/templates/zapros1_output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zapros1</title>
</head>
<style>
    a {
        color: black;
        text-decoration: none;
        font-size: 20px;
    }
</style>
<body>
    <div align="center">
        <table border="1" width="50%" cellpadding="5">
        {% for item in items %}
        <tr>
            {% for key, values in item.items() %}
                <td style="font-size:25px">{{values}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
        </table>
    </div>
    <div align="center">
        <p ><a href="/zapros">Выход в меню</a></p>
    </div>
</body>
</html>

Product_reservation/labs/blueprint_query/templates/zapros2_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zapros2</title>
</head>
<style>
    a {
        color: black;
        text-decoration: none;
        font-size: 30px;
    }
</style>
<body>
        <div align="center">
            <p><font size = 6>Показать все заказы, стоимость которых выше заданного значения</font></p>
            <form action={{url_for('zapros.get_sql2')}} method="post">
                <p><font size = 6>Введите иностранный язык:
                <input type="text" name="lang">
                <input type="submit" name="Отправить">

            </font></p>
            <a href="http://127.0.0.1:5002">Выход в меню</a>
            </form>
        </div>
</body>
</html>

Product_reservation/labs/blueprint_query/templates/zapros2_output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zapros2</title>
</head>
<style>
    a {
        color: black;
        text-decoration: none;
        font-size: 20px;
    }
</style>
<body>
    <div align="center">
        <table border="1" width="40%" cellpadding="5">
        {% for item in items %}
        <tr>
            {% for key, values in item.items() %}
                <td style="font-size:25px">{{values}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
        </table>
    </div>
    <div align="center">
        <p ><a href="/zapros">Выход в меню</a></p>
    </div>
</body>
</html>

Product_reservation/labs/blueprint_query/templates/zaproses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zaproses</title>
</head>
<style>
    a {
        color: black;
        text-decoration: none;
        font-size: 30px;
    }
</style>
<body>
    <div align="center">
            <p><a href="{{url_for('zapros.zaprose1_input')}}">Запрос 1</a></p>
            <p><a href="{{url_for('zapros.zaprose2_input')}}">Запрос 2</a></p>
            <p><a href="http://127.0.0.1:5002">Выход в меню</a></p>
    </div>
</body>
</html>