Product_reservation/labs/scenario_auth/routes.py
from flask import Blueprint, render_template, session, request, current_app
from sql_provider import SQLProvider
from dbcon import get_db_config, work_with_db
import os

auth_app = Blueprint('auth_app', __name__, template_folder='templates')
provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@auth_app.route('/', methods=['GET', 'POST'])
def login_page():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        login = request.form.get('login', '')
        password = request.form.get('password', '')
        sql = provider.get('auth.sql', log=login, pas=password)
        name_group = work_with_db(current_app.config['DB_CONFIG'], sql)
        if not name_group:
            return render_template("index3.html")
        session['group_name'] = name_group[0]['user_group']
        print(session['group_name'])
        return render_template("menu.html")

Product_reservation/labs/scenario_auth/templates/index3.html


{% block titel %}
{% endblock %}

{% block body %}
<div class="container">
  <form action="" method="POST">
         <p>Invalid login or password</p>
  </form>
  <p><a href="/">Назад</a></p>
</div>
{% endblock %}

Product_reservation/labs/scenario_auth/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
  <form action="" method="POST">
    <input type="text" name="login" placeholder="Login">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Отправить">
  </form>
</body>
</html>

Product_reservation/labs/scenario_auth/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
</head>
<style>
    a {
        color: black;
        text-decoration: none;
        font-size: 50px;
    }
</style>
<body>
    <div align="center">
        <p><a href={{url_for('zapros.zaproses')}}>Работа с запросами</a></p>
        <p><a href="{{url_for('reports.report_page')}}">Работа с отчетами</a></p>
        <p><a href="{{url_for('auth_app.login_page')}}">Авторизация</a></p>
        <p><a href="">Выход</a></p>
    </div>
</body>
</html>